apiVersion: v1
kind: Pod
metadata:
  name: non-admin-port
  labels:
    app: non-admin-port
spec:
  imagePullSecrets:
    - name: acr
  containers:
  - name: main
    image: spinsample2.azurecr.io/node:0.0.1
    imagePullPolicy: Always
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    env:
      - name: PORT
        value: "1025"
    livenessProbe:
      httpGet:
        path: healthz
        port: 1025
      initialDelaySeconds: 20
      periodSeconds: 3    
---
apiVersion: v1
kind: Service
metadata:
  name: non-admin-port
spec:
  selector:
    app: non-admin-port
  ports:
  - port: 8080
    targetPort: 1025

